# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05b4063760b72759fe8401b57588ae0727a50e1d4b98281e459f74f615f48ffa4c796992c67f16bb36970e7b5a1d03112428860206c2117a103d9e9b06249b0f

test:
  secret_key_base: 7b46c8d988619178fc328c52e5030c008bb8dad89c2475bcf4d516d905e52f3e5865feb3af8bd159a67ac4624b137b6ee5b52ddfe060dbaa832f29062223b17e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
