# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 987ab2609dc4e0757363f3c7ef379424eddad3414c35e7f76df160ba1c491b1f50093bd622bc52347c0bae3545eef38bcd48be3de37d8b0db2a93e6786a000b8

test:
  secret_key_base: 6816c7bb244c0a0b24832b837e0ccac6c84618c086c8c6021ff3581f8e7486f5f22a7cf91404d96071f82f954f0b528b13c3e40f1603c15c42dcfebe8bb70b46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
